name: CI

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Recommended for SonarCloud
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.15.1
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test:coverage
      - name: fix code coverage paths
        working-directory: ./coverage
        run: |
          sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' lcov.info
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # The build is made by Vercel when deploying
