name: CI

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.15.1
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test
      # The build is made by Vercel when deploying
